add wait task stop

diff --git a/.github/workflows/deno.yml b/.github/workflows/deno.yml
--- a/.github/workflows/deno.yml
+++ b/.github/workflows/deno.yml
@@ -55,37 +55,40 @@ jobs:
         run: |
           rev=`aws ecs describe-task-definition --task-definition msi-be-task-def --region ap-northeast-1 | jq .taskDefinition.revision`
           echo REVISION_BE=$rev >> $GITHUB_ENV
-
+      
       # update ECS Service
       - name: Force deployment
         run: |
+          container_list=$(aws ecs list-tasks --region ap-northeast-1 --cluster msi-cluster --service-name msi-be-service | awk '/msi-cluster/ {print}' | sed 's/,$//' | awk '{ sub(/^[ \t]+/, ""); print }' | awk '{printf "%s ",$0} END {print ""}')
+          echo $container_list
           aws ecs update-service --force-new-deployment --cluster msi-cluster --service msi-be-service --task-definition msi-be-task-def:${{ env.REVISION_BE }} --desired-count 1 --region ap-northeast-1
+          aws ecs wait tasks-stopped --cluster msi-cluster --tasks $container_list
 
       # - name: Wait for service update to stabilize
       #   run: |
       #     aws ecs wait services-stable --cluster  msi-cluster --services msi-be-service --region ap-northeast-1
 
 
-      - name: Send notification to Slack
-        run: |
-          successText=":github: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* completed successfully."
-          failureText=":github: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* failed."
-          cancelledText=":github: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* was cancelled.😥"
-          status="${{ (contains(needs.*.result, 'cancelled') && 'cancelled') || (contains(needs.*.result, 'failure') && 'failure') || 'success' }}"
+      # - name: Send notification to Slack
+      #   run: |
+      #     successText=":github: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* completed successfully."
+      #     failureText=":github: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* failed."
+      #     cancelledText=":github: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* was cancelled.😥"
+      #     status="${{ (contains(needs.*.result, 'cancelled') && 'cancelled') || (contains(needs.*.result, 'failure') && 'failure') || 'success' }}"
 
-          if [ "$status" = 'success' ]; then
-          color='good'
-          text=$successText
-          elif [ "$status" = 'failure' ]; then
-          color='danger'
-          text=$failureText
-          elif [ "$status" = "cancelled" ]; then
-            color='warning'
-            text=$cancelledText
-          fi
+      #     if [ "$status" = 'success' ]; then
+      #     color='good'
+      #     text=$successText
+      #     elif [ "$status" = 'failure' ]; then
+      #     color='danger'
+      #     text=$failureText
+      #     elif [ "$status" = "cancelled" ]; then
+      #       color='warning'
+      #       text=$cancelledText
+      #     fi
 
-          echo "{attachments: [{text: \"$text\", color: \"$color\"}]}" | curl \
-            "${{ secrets.SLACK_WEBHOOK_URL }}" \
-            -X "POST" \
-            --header "Content-Type: application/json" \
-            --data-binary @-                   
+      #     echo "{attachments: [{text: \"$text\", color: \"$color\"}]}" | curl \
+      #       "${{ secrets.SLACK_WEBHOOK_URL }}" \
+      #       -X "POST" \
+      #       --header "Content-Type: application/json" \
+      #       --data-binary @-                   
