add notify slack for test

diff --git a/.github/workflows/deno.yml b/.github/workflows/deno.yml
--- a/.github/workflows/deno.yml
+++ b/.github/workflows/deno.yml
@@ -1,19 +1,26 @@
-name: Deploy to Amazon ECS
+name: Backend Deploy to Amazon ECS 
 
 on:
+  workflow_dispatch:
   push:
     branches:
-      - main
-# permissions:
-#     id-token: write
-#     contents: read
+      - dev
+
+env:
+  ENV_NAME: dev
+  AWS_ROLE_ARN: ${{ secrets.DEV_AWS_ROLE_ARN }}
+  AWS_DEFAULT_REGION: ${{ secrets.DEV_AWS_REGION }}
+  AWS_REGION: ${{ secrets.DEV_AWS_REGION }}
+
 jobs:
   deploy:
     name: Deploy
-    runs-on: ubuntu-latest  
+    runs-on: ubuntu-latest
+    timeout-minutes: 10  
     permissions:
       id-token: write
       contents: read
+  
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -21,18 +28,14 @@ jobs:
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
-          aws-region: ap-northeast-1
-          role-to-assume: arn:aws:iam::430334909132:role/msi-oidc-role
-          role-session-name: msi-oidc-role
-      - name: Sts GetCallerIdentity
-        run: |
-          aws sts get-caller-identity
+          aws-region: ${{ env.AWS_REGION }}
+          role-to-assume: ${{ env.AWS_ROLE_ARN }}
     
       - name: Login to Amazon ECR
-        id: login-ecr
+        id: login-ecr-dev
         uses: aws-actions/amazon-ecr-login@v1
       
-      # # app build 
+      # app build 
       # - name: Docker build and push
       #   id: build-image-app
       #   env:
@@ -44,12 +47,42 @@ jobs:
       #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
       #     echo NEW_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG >> $GITHUB_ENV
 
+      # get latest revision of TaskDefinition
       - name: get version
         run: |
           rev=`aws ecs describe-task-definition --task-definition msi-be-task-def --region ap-northeast-1 | jq .taskDefinition.revision`
           echo REVISION_BE=$rev >> $GITHUB_ENV
 
-      # Update ECS Service
+      # update ECS Service
       - name: Force deployment
         run: |
-          aws ecs update-service --force-new-deployment --cluster msi-cluster --service msi-be-service --task-definition msi-be-task-def:${{ env.REVISION_BE }} --desired-count 1 
+          aws ecs update-service --force-new-deployment --cluster msi-cluster --service msi-be-service --task-definition msi-be-task-def:${{ env.REVISION_BE }} --desired-count 1 --region ap-northeast-1
+
+      - name: Wait for service update to stabilize
+        run: |
+          aws ecs wait services-stable --cluster  msi-cluster --services msi-be-service --region ap-northeast-1
+
+
+      - name: Send notification to Slack
+        run: |
+          successText=":octocat: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* completed successfully."
+          failureText=":octocat: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* failed."
+          cancelledText=":octocat: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* was cancelled.😥"
+          status="${{ (contains(needs.*.result, 'cancelled') && 'cancelled') || (contains(needs.*.result, 'failure') && 'failure') || 'success' }}"
+
+          if [ "$status" = 'success' ]; then
+          color='good'
+          text=$successText
+          elif [ "$status" = 'failure' ]; then
+          color='danger'
+          text=$failureText
+          elif [ "$status" = "cancelled" ]; then
+            color='warning'
+            text=$cancelledText
+          fi
+
+          echo "{attachments: [{text: \"$text\", color: \"$color\"}]}" | curl \
+            "${{ secrets.SLACK_WEBHOOK_URL }}" \
+            -X "POST" \
+            --header "Content-Type: application/json" \
+            --data-binary @-                   
